VERSION="2.2.1"

ACCOUNTS=["GAFMAA63BAHHCAL7SK4SRWLDBHY7JTTMS732KSLPUVLJZ6IIRNFAUDDB"]

[DOCUMENTATION]
ORG_NAME="De Beers"
ORG_URL="https://www.stellar-db.org/"
ORG_DESCRIPTION="The De Beers Group is a South African-British corporation that specializes in the diamond industry, including mining, exploitation, retail, inscription, grading, trading and industrial diamond manufacturing."
ORG_LOGO="https://www.stellar-db.org/db.png"


[[CURRENCIES]]
code="DEBEERS"
status="live"
display_decimals=2
issuer="GAFMAA63BAHHCAL7SK4SRWLDBHY7JTTMS732KSLPUVLJZ6IIRNFAUDDB"
anchor_asset_type="crypto"
name="De Beers"
desc="The De Beers Group is a South African-British corporation that specializes in the diamond industry, including mining, exploitation, retail, inscription, grading, trading and industrial diamond manufacturing."
image="https://www.stellar-db.org/db.png"
